---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: mhart/alpine-node
    tag: latest

inputs:
  - name: service-repo

run:
  path: service-repo/ci/tasks/build-service/task.sh
